//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCode
{
    public partial class Sales_POS_ItemCode_ItemCodeViewPopUp
    {
        protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected global::Telerik.Web.UI.RadTextBox txtItemCode;
        protected global::Telerik.Web.UI.RadTextBox txtItemGroupCode;
        protected global::Telerik.Web.UI.RadTextBox txtItemDesc;
        protected global::Telerik.Web.UI.RadTextBox txtUnitPrice;
        protected global::Telerik.Web.UI.RadTextBox txtUnitTax;
        protected global::Telerik.Web.UI.RadTextBox txtCurQty;
        protected global::Telerik.Web.UI.RadTextBox txtTotalPrice;
        protected global::Telerik.Web.UI.RadTextBox txtSQLAccCode;
        protected global::Telerik.Web.UI.RadTextBox txtSQLAccTaxCode;
        protected global::Telerik.Web.UI.RadButton BtnWeb;
        protected global::Telerik.Web.UI.RadButton BtnLover;
        protected global::Telerik.Web.UI.RadButton BtnLSD;
        protected global::Telerik.Web.UI.RadButton ChkSelfPickUp;
        protected global::Telerik.Web.UI.RadButton ChkDelivery;
        protected global::Telerik.Web.UI.RadTextBox txtRemark;
        protected global::System.Web.UI.WebControls.Image ImageID;
    }
}
