//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCode
{
    public partial class Sales_POS_ItemCode_ItemBankStockMonitoringEntry
    {
        protected global::Telerik.Web.UI.RadWindowManager RadWindowManager1;
        protected global::Telerik.Web.UI.RadAjaxLoadingPanel RadAjaxLoadingPanel1;
        protected global::Telerik.Web.UI.RadAjaxManagerProxy RadAjaxManagerProxy1;
        protected global::Telerik.Web.UI.RadAjaxPanel RadAjaxPanel1;
        protected global::System.Web.UI.WebControls.Button btnHidden;
        protected global::Telerik.Web.UI.RadMonthYearPicker mypStockMonth;
        protected global::Telerik.Web.UI.RadButton btnSearch;
        protected global::Telerik.Web.UI.RadButton btnClear;
        protected global::System.Web.UI.WebControls.Panel Panel1;
        protected global::Telerik.Web.UI.RadGrid RadGrid_ItemBank;
        protected global::Telerik.Web.UI.RadButton btnSave;
        protected global::Telerik.Web.UI.RadButton btnConfirm;
    }
}
