//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCode
{
    public partial class Sales_POS_ItemCode_ItemCodeEditPopUp
    {
        protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected global::Telerik.Web.UI.RadWindowManager RadWindowManager1;
        protected global::Telerik.Web.UI.RadWindow WindowPopup;
        protected global::Telerik.Web.UI.RadTextBox txtItemCode;
        protected global::System.Web.UI.WebControls.HiddenField hiddenItemGrpID;
        protected global::Telerik.Web.UI.RadComboBox cmbItem_Type;
        protected global::Telerik.Web.UI.RadTextBox txtDesc;
        protected global::Telerik.Web.UI.RadTextBox txtUnitPrice;
        protected global::Telerik.Web.UI.RadTextBox txtUnitTax;
        protected global::Telerik.Web.UI.RadNumericTextBox txtCurQty;
        protected global::Telerik.Web.UI.RadNumericTextBox txtItemPrice;
        protected global::Telerik.Web.UI.RadTextBox txtSQLACCCode;
        protected global::Telerik.Web.UI.RadTextBox txtTaxCode;
        protected global::System.Web.UI.WebControls.HiddenField HiddenFieldName;
        protected global::System.Web.UI.WebControls.HiddenField HiddenDay;
        protected global::System.Web.UI.WebControls.HiddenField HiddenMonth;
        protected global::System.Web.UI.WebControls.HiddenField HiddenYear;
        protected global::Telerik.Web.UI.RadButton BtnWeb;
        protected global::Telerik.Web.UI.RadButton BtnLover;
        protected global::Telerik.Web.UI.RadButton BtnLSD;
        protected global::Telerik.Web.UI.RadButton BtnWST;
        protected global::Telerik.Web.UI.RadButton BtnYesSelfPickUp;
        protected global::Telerik.Web.UI.RadButton BtnNoSelfPickUp;
        protected global::Telerik.Web.UI.RadButton BtnYesDelivery;
        protected global::Telerik.Web.UI.RadButton BtnNoDelivery;
        protected global::Telerik.Web.UI.RadTextBox txtRemark;
        protected global::System.Web.UI.WebControls.Image ImageID;
        protected global::Telerik.Web.UI.RadAsyncUpload RadAsyncUpload1;
        protected global::Telerik.Web.UI.RadCheckBox cbEnabled;
        protected global::Telerik.Web.UI.RadButton btnEdit;
    }
}
