//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCode
{
    public partial class Sales_POS_ItemCode_ItemCodeSearch
    {
        protected global::Telerik.Web.UI.RadWindowManager RadWindowManager1;
        protected global::Telerik.Web.UI.RadWindow WindowPopup;
        protected global::Telerik.Web.UI.RadWindow WindowAction;
        protected global::System.Web.UI.WebControls.HiddenField hiddenSelection;
        protected global::Telerik.Web.UI.RadTextBox txtAction1;
        protected global::Telerik.Web.UI.RadTextBox txtSelection;
        protected global::Telerik.Web.UI.RadTextBox txtAction2;
        protected global::Telerik.Web.UI.RadComboBox cmbAction;
        protected global::Telerik.Web.UI.RadButton btnProceed;
        protected global::Telerik.Web.UI.RadComboBox cmbItem_Type;
        protected global::Telerik.Web.UI.RadTextBox txtItemCode;
        protected global::Telerik.Web.UI.RadTextBox txtItemDesc;
        protected global::Telerik.Web.UI.RadComboBox cmbIsNE;
        protected global::Telerik.Web.UI.RadComboBox cmbIsLSD;
        protected global::Telerik.Web.UI.RadGrid RadGrid_ItemCode;
    }
}
