//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemCode
{
    public partial class Sales_POS_ItemCode_ItemCodeAdjustmentEntry
    {
        protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected global::Telerik.Web.UI.RadWindowManager RadWindowManager1;
        protected global::Telerik.Web.UI.RadAjaxManager RadAjaxManager1;
        protected global::Telerik.Web.UI.RadAjaxLoadingPanel RadAjaxLoadingPanel1;
        protected global::Telerik.Web.UI.RadAjaxPanel RadAjaxPanel1;
        protected global::Telerik.Web.UI.RadTextBox txtItemCode;
        protected global::Telerik.Web.UI.RadTextBox txtItemDesc;
        protected global::Telerik.Web.UI.RadComboBox cmbAdjType;
        protected global::Telerik.Web.UI.RadComboBox cmbReason;
        protected global::Telerik.Web.UI.RadTextBox txtCurQty;
        protected global::Telerik.Web.UI.RadNumericTextBox txtQuantity;
        protected global::Telerik.Web.UI.RadTextBox txtRemark;
        protected global::Telerik.Web.UI.RadButton BtnSave;
        protected global::Telerik.Web.UI.RadButton BtnClear;
    }
}
